### ISSUE TITLE
Убрать dispatch из API

### ISSUE THREAD

**Issue by Rastopyr** [OlegKotsubko/prjctr#2]
https://github.com/OlegKotsubko/prjctr/blob/71c1debdcaf2b840c4112a4ebd90d6a7212b538d/src/contexts/NotesContext.js#L37

То что dispatch торчит наружу, не есть хорошо

1. Любой потрбитель может задиспатчить что угодно
2. Если будет меняться реализация стейт менеджера то это по касательной затронет всех потребителей которые на него завязаны
3. Лучше использовать конкретный метод чем обший

**Comment by OlegKotsubko** [comment]
Dispatch has been removed from notes context provider and created special methods:

- addNote
- editNote
- deleteNote
